import './globals.css'
import Providers from '@/components/Providers'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata = {
  title: 'Msg.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>
  <html lang="en" suppressHydrationWarning>
    <head />
    <body>
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
      >
        {children}
      </ThemeProvider>
    </body>
  </html>
</>
}
